version: '3.8'

# This is an example override file that shows all available configuration options
# Copy to docker-compose.override.yml and modify as needed

services:
  api:
    environment:
      # API configuration
      - PIXELETICA_API_HOST=0.0.0.0 
      - PIXELETICA_API_PORT=8000
      - REDIS_URL=redis://redis:6379/0
      
      # Enable debug output
      # - LOG_LEVEL=debug
      
      # Additional API settings
      # - CORS_ORIGINS=http://localhost:3000,https://example.com
      # - MAX_UPLOAD_SIZE=10485760  # 10MB
      
    # Uncomment to restart automatically on failure
    # restart: always
    
    # Uncomment to expose additional ports
    # ports:
    #  - "8000:8000"
    
    # Uncomment to mount source code for development
    # volumes:
    #  - ./pixeletica:/app/pixeletica
    #  - pixeletica_data:/app/tasks

  worker:
    environment:
      # Worker configuration
      - REDIS_URL=redis://redis:6379/0
      
      # Concurrency settings
      # - CELERY_CONCURRENCY=4  # Number of worker processes
      
      # Task time limits
      # - CELERY_TASK_TIME_LIMIT=3600  # 1 hour
      # - CELERY_TASK_SOFT_TIME_LIMIT=3000  # 50 minutes
      
      # Additional worker settings
      # - LOG_LEVEL=info
      # - CELERY_MAX_TASKS_PER_CHILD=100
    
    # Uncomment to restart automatically on failure
    # restart: always
    
    # Uncomment to mount source code for development
    # volumes:
    #  - ./pixeletica:/app/pixeletica
    #  - pixeletica_data:/app/tasks

  redis:
    # Use Alpine for smaller image or full Redis for more features
    image: redis:7-alpine
    
    # Redis server configuration
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy volatile-lru
    
    # Uncomment to expose Redis port (for development only)
    # ports:
    #  - "6379:6379"
    
    # Uncomment for custom Redis configuration
    # volumes:
    #  - ./config/redis.conf:/usr/local/etc/redis/redis.conf
    #  - redis_data:/data
